name: replace-github-secrets
description: Replace placeholders with values from GitHub Secrets
author: Kevin Tijssen (TNO)

inputs:
  directory:
    description: "Directory where files containing placeholders are located"
    default: "."
  publicCert:
    description:  "Context or environment containing the necessary secrets for replacement. This parameter is required and should provide the necessary secret values for replacing placeholders in the files."
    required: true
  prefix: 
    description: "Prefix for secret placeholders in files"

runs:
  using: "composite"
  steps:
    - name: Seal each secret with SealedSecrets
      shell: bash
      run: |

        # Seal each secret with SealedSecrets
        
        echo "${{ inputs.publicCert }}" > public-cert.pem
        # Loop through each file in the specified directory that matches the project name pattern
        for FILE in $(find ${{ inputs.directory }} -type f -name '${{ inputs.prefix }}*'); do
          cat $FILE
          mv $FILE $FILE.tmp
          kubeseal --format yaml --cert public-cert.pem --scope cluster-wide < $FILE.tmp > $FILE
          cat $FILE
        done
