name: cleanup-artifacts
description: Delete all files in the artifacts directory
author: Kevin Tijssen (TNO)

runs:
  using: "composite"
  steps:
    - name: Cleanup artifacts directory
      shell: bash --noprofile --norc -o pipefail {0}
      run: |

        # Delete old pipeline runs
        if [ -d "~/artifacts/${github.repository}/${github.run_id}" ]; then
          rm -rf ~/artifacts/${github.repository}/${github.run_id} &>/dev/null
        fi

        # Delete all files that are older than 7 days
        if [ -d "~/artifacts/${{ github.repository_owner }}" ]; then
          find ~/artifacts/${{ github.repository_owner }} -maxdepth 2 -mtime +7 -type d | xargs rm -rf &>/dev/null
        fi