name: Setup Kustomize
description: Setup Kustomize in your environment
author: Kevin Tijssen

inputs:
  version: 
    description: "Which version do you want to install?"
    default: 'latest'

runs:
  using: "composite"
  steps:
    - name: Download Kustomize from GitHub
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin/
        if [[ ${{ inputs.version }} != "latest" ]]; then
          curl -sL "https://get.helm.sh/helm-${{ inputs.version }}-linux-amd64.tar.gz" -o "helm.tar.gz"
        else
          VERSION=$(curl -s https://api.github.com/repos/helm/helm/releases/latest | jq -r .name | cut -d ' ' -f2)
          curl -sL "https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz" -o "helm.tar.gz"
        fi
        tar -xf "helm.tar.gz" linux-amd64/helm
        sudo install -o root -g root -m 0755 linux-amd64/helm /usr/local/bin/helm
    # - name: Show installed version
    #   shell: bash
    #   run: |
    #     kustomize version