name: E2E

on:
  workflow_call:

jobs:
  runE2ETest:
    name: Run E2E Test
    runs-on: [self-hosted]
    if: ${{ github.event.inputs.run_e2e_test == 'true' }}
    continue-on-error: true
    steps:
      - name: Start script
        shell: bash
        run: |
          echo "Run E2E test"