apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: memory-limits
spec:
  validationFailureAction: audit
  background: true
  rules:
  - name: memory-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Memory resource limits are required."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                memory: "?*"