apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: multiple-replicas
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: multiple-replicas
      match:
        resources:
          kinds:
          - Deployment
      validate:
        message: "Deployments should have more than one replica to ensure availability."
        pattern:
          spec:
            replicas: ">1"