name: Manifests

on:
  workflow_call:
    inputs:
      projectName:
        default: ${{ github.workflow }}
        required: false
        type: string
      containerRegistry:
        default: ''
        required: false
        type: string
      gitTag:
        required: true
        type: string

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v3
      # - name: Check out global-actions repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: KTijssen/global-actions
      #     ref: beta
      #     # token: ${{ secrets.PAT_TOKEN }}
      #     path: "global-actions"

      - name: Replace variables in Kubernetes Manifests
        shell: bash
        working-directory: ./kubernetes
        run: |
          echo "Applying build version to Kubernetes manifests"
          find . -type f -exec sed -i "s!%IMAGE_VERSION%!${{ inputs.gitTag }}!g" {} \;

          echo "Applying servicename to Kubernetes manifests"
          find . -type f -exec sed -i "s!%SERVICE_NAME%!${{ inputs.projectName }}!g" {} \;

          echo "Applying container registry to templates"
          if [[ ! ${{ inputs.containerRegistry }} ]]; then
            find . -type f -exec sed -i "s!%IMAGE_HOST%/!${{ inputs.containerRegistry }}!g" {} \;
          else
            find . -type f -exec sed -i "s!%IMAGE_HOST%!${{ inputs.containerRegistry }}!g" {} \;
          fi

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: latest
          
      - name: Generate Kubernetes YAML
        shell: bash
        working-directory: ./kubernetes
        run: |
          kubectl kustomize ./overlays/test > ./${{ inputs.projectName }}-test-kubernetes.yaml
          cat ./${{ inputs.projectName }}-test-kubernetes.yaml