name: common

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
        default: 0
      minor:
        required: true
        type: string
        default: 0
    secrets:
      patch:
        required: true
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    steps:
      - name: Get variables
        uses: actions/labeler@v4
        with:
          major: ${{ inputs.major }}
          minor: ${{ inputs.minor }}
          patch: ${{ secrets.patch }}
      - name: Get version number
        shell: bash
        run: |
          env
          ./global-actions/common.sh
