name: common

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
        default: 0
      minor:
        required: true
        type: string
        default: 0
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v3
      - name: Download Global Actions artifact
        uses: actions/download-artifact@v3
        with:
          name: global-actions
          path: ./global-actions
      - name: Get version number
        id: tag
        shell: bash
        run: |
          ls -la
          git tag
          ./global-actions/common.sh
          
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}
      # - name: Create git-tag artifact
      #   uses: actions/upload-artifact@master
      #   with:
      #     name: git-tag
      #     path: ./git_tag.file