name: common

on:
  workflow_call:
    secrets:
      envPATCH:
        required: true
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    steps:
      - name: Get version number
        shell: bash
        run: |
          env
          ./global-actions/common.sh
        with:
          patch: ${{ secrets.PATCH }}