name: common

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
        default: 0
      minor:
        required: true
        type: string
        default: 0
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    steps:
      # - name: Check out local project repository
      #   uses: actions/checkout@v3
      - name: Get version number
        id: tag
        shell: bash
        run: |
          ./global-actions/common.sh
          ls -la
          $PWD
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}