name: common

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
        default: 0
      minor:
        required: true
        type: string
        default: 0
    outputs:
      git_tag:
        description: "Tag to use for build docker/manifest files"
        value: ${{ jobs.SetVersion.outputs1 }}
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    steps:
      # - name: Check out local project repository
      #   uses: actions/checkout@v3
      - name: Get version number
        id: tag
        shell: bash
        run: |
          ./global-actions/common.sh
          env   
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}
    outputs:
      output1: ${{ steps.tag.outputs.git_tag }}