name: common

on:
  workflow_call:
    
jobs:
  SetVersion:
    name: Semantic Versioning
    needs: checkout
    runs-on: [self-hosted]
    steps:
      - name: Get version number
        shell: bash
        run: ./global-actions/common.sh