name: common

on:
  workflow_call:
    inputs:
      major:
        required: true
        type: string
        default: 0
      minor:
        required: true
        type: string
        default: 0
    outputs:
      gitTag:
        value: $${{jobs.SetVersion.outputs.gitTag}}
    secrets:
      PAT_TOKEN:
        required: true
    
jobs:
  SetVersion:
    name: Semantic Versioning
    runs-on: [self-hosted]
    outputs:
      gitTag: $${{ steps.tag.outputs.gitTag}}
    steps:
      - name: Checkout Project Repo
        uses: actions/checkout@v3
      - name: Check out global-actions repository
        uses: actions/checkout@v3
        with:
          repository: KTijssen/global-actions
          ref: beta
          token: ${{ secrets.PAT_TOKEN }}
          path: "global-actions"
      - name: Get version number
        id: tag
        shell: bash
        run: ./global-actions/common.sh
        env:
          MAJOR: ${{ inputs.major }}
          MINOR: ${{ inputs.minor }}
      - name: Create gitTag artifact
        uses: actions/upload-artifact@master
        with:
          name: gitTag
          path: ./gitTag.file
          retention-days: 1