name: Deployment

on:
  workflow_call:

jobs:
  GlobalDeployment:
    name: Global Deployment checks
    runs-on: [self-hosted]
    steps:
      - name: Check Rego Policies
        shell: bash
        run: ./global-actions/deployment/deployment_check_policies.sh

  DeployToTest:
    name: Deploy to Test
    needs: GlobalDeployment
    runs-on: [self-hosted]
    steps:
      - name: Deploy to Test
        shell: bash
        run: ./global-actions/deployment/deployment_push2repo.sh
        env:
          OC_ENV: Test

  RunE2ETest:
    name: Tests
    needs: DeployToTest
    if: ${{ github.event.inputs.run_e2e_test == 'true' }}
    uses: KTijssen/global-actions/.github/workflows/e2e.yaml@main

  DeployToAccept:
    name: Deploy to Accept
    needs: [DeployToTest, RunE2ETest]
    runs-on: [self-hosted]
    environment: Acceptance
    steps:
      - name: Deploy to Accept
        shell: bash
        run: ./global-actions/deployment/deployment_push2repo.sh
        env:
          OC_ENV: Accept