name: E2E

on:
  workflow_call:

jobs:
  runE2ETest:
    name: Run E2E Test
    runs-on: [self-hosted]
    continue-on-error: true
    steps:
      - name: Start script
        shell: bash
        run: ./global-actions/deployment/deployment_push2repo.sh