name: Deployment

on:
  workflow_call:

jobs:
  checkPolicies:
    name: Global Deployment checks
    uses: ./.github/workflows/policies_rego.yaml

  deployToDev:
    name: ...
    needs: checkPolicies
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Development
      namespace: bro-lv-dev

  deployToTest:
    name: ...
    needs: deploytoDev
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Test
      namespace: bro-lv-tst

  runE2ETest:
    name: ...
    needs: DeployToTest
    if: ${{ github.event.inputs.run_e2e_test == 'true' }}
    uses: ./.github/workflows/e2e.yaml

  DeployToProd:
    name: ...
    needs: [checkPolicies, deployToDev]
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Production
      namespace: bro-lv-prd
      approval: production