name: Deployment

on:
  workflow_call:

jobs:
  GlobalDeployment:
    name: Global Deployment checks
    runs-on: [self-hosted]
    steps:
      - name: Check Rego Policies
        shell: bash
        run: ./global-actions/deployment/deployment_check_policies.sh