name: Deployment

on:
  workflow_call:

jobs:
  checkPolicies:
    name: Global Deployment checks
    uses: ./.github/workflows/policies_rego.yaml

  deployToDev:
    name: ...
    needs: checkPolicies
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Development
      namespace: bro-lv-dev

  deployToTest:
    name: ...
    needs: deploytoDev
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Test
      namespace: bro-lv-tst

  runE2ETest:
    name: ...
    needs: DeployToTest
    uses: ./.github/workflows/e2e.yaml

  deployToAccept:
    name: ...
    needs: [runE2ETest, deployToTest]
    if: | 
      (github.ref_name == 'main' || github.ref_name == 'master') &&
      (needs.runE2ETest.result == 'success' || needs.runE2ETest.result == 'skipped')
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Acceptance
      namespace: bro-lv-acc
      approval: acceptance

  deployToInt:
    name: ...
    needs: deployToAccept
    if: | 
      github.ref_name == 'main' || github.ref_name == 'master'
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Integration
      namespace: bro-lv-int
      approval: integration

  deployToProd:
    name: ...
    needs: deployToInt
    if: |
      github.ref_name == 'main' || github.ref_name == 'master'
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      deployEnv: Production
      namespace: bro-lv-prd
      approval: production