name: Deployment

on:
  workflow_call:

jobs:
  checkPolicies:
    name: Global Deployment checks
    uses: ./.github/workflows/policies_rego.yaml

  DeployToDev:
    name: .
    needs: checkPolicies
    uses: ./.github/workflows/kubernetes_stage.yaml
    with:
      oc_env: Development

  # DeployToTest:
  #   name: Deploy to Test
  #   needs: GlobalDeployment
  #   runs-on: [self-hosted]
  #   steps:
  #     - name: Deploy to Test
  #       shell: bash
  #       run: ./global-actions/deployment/deployment_push2repo.sh
  #       env:
  #         OC_ENV: Test

  # RunE2ETest:
  #   name: Tests
  #   needs: DeployToTest
  #   if: ${{ github.event.inputs.run_e2e_test == 'true' }}
  #   uses: KTijssen/global-actions/.github/workflows/e2e.yaml@main

  # DeployToAccept:
  #   name: Deploy to Accept
  #   needs: DeployToTest
  #   runs-on: [self-hosted]
  #   environment: Acceptance
  #   steps:
  #     - name: Deploy to Accept
  #       shell: bash
  #       run: ./global-actions/deployment/deployment_push2repo.sh
  #       env:
  #         OC_ENV: Accept