name: Manifests

on:
  workflow_call:
    inputs:
      git_tag:
        required: false
        type: string

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Build Manifest
        shell: bash
        run: ./global-actions/build/manifests/build_manifests.sh
        env:
          GIT_TAG: ${{ inputs.git_tag }}