name: Manifests

on:
  workflow_call:
    inputs:
      gitTag:
        type: string
        required: true

env:
  containerRegistry: ''

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Build Manifest
        shell: bash
        run: |
          echo ${{ inputs.gitTag }}
          ./global-actions/build/manifests/build_manifests.sh