name: Manifests

on:
  workflow_call:

env:
  containerRegistry: ''

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Build Manifest
        shell: bash
        run: |
          ./global-actions/build/manifests/build_manifests.sh