name: Manifests

on:
  workflow_call:
    inputs:
      projectName:
        default: ${{ github.workflow }}
        required: false
        type: string
      containerRegistry:
        default: ''
        required: false
        type: string
      gitTag:
        required: true
        type: string

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Build Manifest
        shell: bash
        run: |
          echo ${{ inputs.gitTag }}
          ./global-actions/build/manifests/build_manifests.sh