name: common

on:
  workflow_call:

jobs:
  BuildManifests:
    name: Build Manifests files
    runs-on: [self-hosted]
    steps:
      - name: Build Manifest
        shell: bash
        run: ./global-actions/build/manifests/build_manifests.sh