name: Maven

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_RO_TOKEN:
        required: true


jobs:

  BuildAndTest:
    name: Maven Build & Test
    runs-on: [self-hosted]
    steps:
      - name: Maven Build
        shell: bash
        run: ./global-actions/build/maven/build_maven.sh

  BuildContainerImage:
    name: Build & Push Container Image
    needs: BuildAndTest
    runs-on: [self-hosted]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_RO_TOKEN }}
      - name: Build & Push
        shell: bash
        run: ./global-actions/build/maven/build_docker-container.sh