name: Maven

on:
  workflow_call:
    inputs:
      projectName:
        type: string
        required: true
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_RO_TOKEN:
        required: true

jobs:

  BuildAndTest:
    name: Maven Build & Test
    runs-on: [self-hosted]
    steps:
      - name: Maven Build
        shell: bash
        run: ./global-actions/build/maven/build_maven.sh

  BuildContainerImage:
    name: Build & Push Container Image
    needs: BuildAndTest
    runs-on: [self-hosted]
    steps:

      - name: Download GitTag artifact
        uses: actions/download-artifact@v3
        with:
          name: gitTag
          path: ./artifacts

      - name: Get gitTag from file
        id: get-gitTag
        run: echo "gitTag=$(cat ./artifacts/gitTag.file)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_RO_TOKEN }}

      - name: Build Container Image (Main/Master)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name == 'main' || github.ref_name == 'master'
        with:
          command: build
          name: kevintijssen/${{ inputs.projectName }}
          tags: ${{ steps.get-gitTag.outputs.gitTag }}, latest

      - name: Build Container Image (nonMain/nonMaster)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name != 'main' || github.ref_name != 'master'
        with:
          command: build
          name: kevintijssen/${{ inputs.projectName }}
          tags: ${{ steps.get-gitTag.outputs.gitTag }}

      - name: Push Container Image (Main/Master)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name == 'main' || github.ref_name == 'master'
        with:
          command: push
          name: kevintijssen/${{ inputs.projectName }}
          tags: ${{ steps.get-gitTag.outputs.gitTag }}, latest

      - name: Push Container Image (nonMain/nonMaster)
        uses: kevintijssen/docker-build-push@v1
        if: github.ref_name != 'main' || github.ref_name != 'master'
        with:
          command: push
          name: kevintijssen/${{ inputs.projectName }}
          tags: ${{ steps.get-gitTag.outputs.gitTag }}